platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'XZMathEditor_Example' do
  pod 'XZMathEditor', :path => '../'

  target 'XZMathEditor_Tests' do
    inherit! :search_paths

    
  end
end
